version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - node.name=es-dev-node
      - cluster.name=es-dev-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  esinit:
    build: ./esinit
    container_name: esinit
    environment:
      - ES_HOST=elasticsearch
    depends_on:
      - elasticsearch
volumes:
  esdata:
